# Generated by Django 6.0.3 on 2026-03-11 00:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dog', '0002_alter_dog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
