# Generated by Django 6.0.3 on 2026-03-12 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dog', '0003_dog_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence', models.CharField(max_length=255)),
                ('number_people', models.CharField(max_length=255)),
                ('children', models.CharField(max_length=255)),
                ('dog_stay_day', models.CharField(max_length=255)),
                ('dog_sleep_night', models.CharField(max_length=255)),
                ('dog_exercise', models.CharField(max_length=255)),
                ('have_owned_dog', models.CharField(max_length=255)),
                ('if_yes', models.CharField(max_length=255)),
                ('have_you_ever', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dog.dog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
