# Generated by Django 6.0.3 on 2026-03-10 23:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='avatars/'),
            preserve_default=False,
        ),
    ]
