# Generated by Django 6.0.3 on 2026-03-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_role_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('animal_lover', 'Animal Lover'), ('dog_lover', 'Dog Lover'), ('pet_friend', 'Pet Friend'), ('dog_enthusiast', 'Dog Enthusiast'), ('volunteer', 'Volunteer'), ('rescue_volunteer', 'Rescue Volunteer'), ('shelter_helper', 'Shelter Helper'), ('community_helper', 'Community Helper'), ('pet_care_volunteer', 'Pet Care Volunteer'), ('animal_care_assistant', 'Animal Care Assistant'), ('dog_trainer', 'Dog Trainer'), ('puppy_socializer', 'Puppy Socializer'), ('foster_parent', 'Foster Parent'), ('foster_hero', 'Foster Hero'), ('dog_rescuer', 'Dog Rescuer'), ('adoption_advocate', 'Adoption Advocate'), ('adoption_ambassador', 'Adoption Ambassador'), ('rescue_supporter', 'Rescue Supporter'), ('animal_welfare_supporter', 'Animal Welfare Supporter'), ('rescue_hero', 'Rescue Hero')], max_length=100),
        ),
    ]
