# Generated by Django 6.0.3 on 2026-03-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_role_remove_user_role_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
